spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 20
            response-timeout: 200ms
          routes:
            - id: delivery-tracking-route
              uri: lb://delivery-tracking
              predicates:
                - Path=/api/v1/deliveries/**
                - Method=GET,POST,PUT,OPTIONS
              filters:
                - name: Retry
                  args:
                    retries: 3
                    methods: GET,PUT
                    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY
                    backoff:
                      firstBackoff: 20ms
                      maxBackoff: 50ms
                      factor: 2
                    timeout: 300ms
                - name: CircuitBreaker
                  args:
                    name: delivery-tracking-route-circuit-breaker
                    statusCodes:
                      - 500
                      - 502
                      - 504
            - id: courier-management-route
              uri: lb://courier-management
              predicates:
                - Path=/api/v1/couriers/**
                - Method=GET,POST,PUT,OPTIONS
            - id: courier-management-public-route
              uri: lb://courier-management
              predicates:
                - Path=/api/v1/public/couriers
                - Method=GET
              filters:
                - RewritePath=/api/v1/public/couriers, /api/v1/couriers
                - RemoveJsonAttributesResponseBody=pendingDeliveries,pendingDeliveryQuantity,phone,true
            - id: courier-management-public-segments-route
              uri: lb://courier-management
              predicates:
                - Path=/api/v1/public/couriers/**
                - Method=GET
              filters:
                - RewritePath=/api/v1/public/couriers/?(?<segment>.*), /api/v1/couriers/$\{segment}
                - RemoveJsonAttributesResponseBody=pendingDeliveries,pendingDeliveryQuantity,phone,true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      delivery-tracking-route-circuit-breaker:
        baseConfig: default
        waitDurationInOpenState: 5000

server:
  port: ${APP_SERVER_PORT}
