services:
  postgres:
    container_name: postgres
    image: postgres:17.10-alpine
    restart: unless-stopped
    shm_size: 64mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M
    security_opt:
      - no-new-privileges:true
    networks:
      - tgfdelivery-net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.5
    restart: unless-stopped
    shm_size: 64mb
    depends_on:
      - postgres
    ports:
      - "8083:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dba@tgfdelivery.com
      PGADMIN_DEFAULT_PASSWORD: tgfdelivery
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M
    networks:
      - tgfdelivery-net

volumes:
  postgres_data:
    name: postgres_data
    driver: local
  pgadmin_data:
    name: pgadmin_data
    driver: local

networks:
  tgfdelivery-net:
    driver: bridge