spring:
  application:
    name: courier-management
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/courierdb
    username: postgres
    password: postgres
  mvc:
    apiversion:
      required: true
      detect-supported: true
      supported:
        - 1
      use:
        path-segment: 1
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
    deserialization:
      fail-on-unknown-properties: true
    datatype:
      datetime:
        write-date-keys-as-timestamps: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: courier-management
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.type.mapping:
          delivery-placed-event:com.tgfcodes.tgfdelivery.courier.management.infrastructure.event.DeliveryPlacedIntegrationEvent,
          delivery-picked-up-event:com.fasterxml.jackson.databind.JsonNode,
          delivery-fulfilled-event:com.tgfcodes.tgfdelivery.courier.management.infrastructure.event.DeliveryFulFilledIntegrationEvent

server:
  port: 8080