spring:
  application:
    name: courier-management
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  datasource:
    url: jdbc:${DATABASE_ENGINE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  mvc:
    apiversion:
      required: true
      detect-supported: true
      supported:
        - 1
      use:
        path-segment: 1
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
    deserialization:
      fail-on-unknown-properties: true
    datatype:
      datetime:
        write-date-keys-as-timestamps: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: courier-management
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.type.mapping:
          delivery-placed-event:com.tgfcodes.tgfdelivery.courier.management.infrastructure.event.DeliveryPlacedIntegrationEvent,
          delivery-picked-up-event:com.fasterxml.jackson.databind.JsonNode,
          delivery-fulfilled-event:com.tgfcodes.tgfdelivery.courier.management.infrastructure.event.DeliveryFulFilledIntegrationEvent
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true

server:
  port: ${APP_SERVER_PORT}