spring:
  application:
    name: delivery-tracking
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: postgres
    password: postgres
  mvc:
    apiversion:
      required: true
      detect-supported: true
      supported:
        - 1
      use:
        path-segment: 1
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
    deserialization:
      fail-on-unknown-properties: true
    datatype:
      datetime:
        write-date-keys-as-timestamps: false

server:
  port: 8081