spring:
  application:
    name: delivery-tracking
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  datasource:
    url: jdbc:${DATABASE_ENGINE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  mvc:
    apiversion:
      required: true
      detect-supported: true
      supported:
        - 1
      use:
        path-segment: 1
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
    deserialization:
      fail-on-unknown-properties: true
    datatype:
      datetime:
        write-date-keys-as-timestamps: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping:
          delivery-placed-event:com.tgfcodes.tgfdelivery.delivery.tracking.domain.event.DeliveryPlacedEvent,
          delivery-picked-up-event:com.tgfcodes.tgfdelivery.delivery.tracking.domain.event.DeliveryPickUpEvent,
          delivery-fulfilled-event:com.tgfcodes.tgfdelivery.delivery.tracking.domain.event.DeliveryFulfilledEvent
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 2
        waitDuration: 50ms
    instances:
      Retry_CourierAPIClient_payoutCalculation:
        baseConfig: default
        max-attempts: 3
      retry-exceptions:
        - org.springframework.web.client.ResourceAccessException
      ignoreExceptions:
        - org.springframework.web.client.HttpServerErrorException
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      CircuitBreaker_CourierAPIClient_payoutCalculation:
        baseConfig: default
        waitDurationInOpenState: 5000

server:
  port: ${APP_SERVER_PORT}