services:
  postgres:
    extends:
      file: ../../docker-compose.yaml
      service: postgres

  kafka:
    extends:
      file: ../../docker-compose.yaml
      service: kafka

volumes:
  postgres_data:
    name: postgres_data
  kafka_data:
    name: kafka_data

networks:
  tgfdelivery-net:
    name: tgfdelivery-net
    driver: bridge